const routes = [
  '/',
  '/about',
  '/sponsors',
  '/speakers',
  '/agenda/unpublish',
  '/team',
  '/speakers/kuku',
  '/speakers/hunter',
  '/speakers/serko',
  '/speakers/ray',
  '/speakers/kuro',
  '/team/alex-liu',
  '/team/anan',
  '/team/sova-yu',
  '/team/meinan',
  '/team/rafael',
  '/team/benny',
  '/team/hannah',
  '/team/z',
  '/team/chilun',
  '/team/mo',
  '/team/mike',
  '/team/noah',
  '/team/wujue',
  '/team/antonio',
] as const

export const prerenderConfig = {
  routes,
} as const
